import type { Metadata } from "next";
import { LegalPage } from "../legal";

export const metadata: Metadata = {
  title: "Copyright Notice",
  description: "Copyright notice for NAM Tools content, pages, tools and outputs.",
};

export default function Page() {
  return (
    <LegalPage
      title="Copyright"
      intro="This notice explains the intended position for NAM Tools content and generated outputs."
      body={[
        "NAM Tools page copy, tool structure, original content, layouts and materials are protected by copyright unless stated otherwise.",
        "You may use outputs generated by the tools for your own internal commercial planning, customer preparation, meeting notes and business documents.",
        "You may adapt generated outputs for your own legitimate business use, but you remain responsible for checking the content and numbers before use.",
        "You may not copy, scrape, resell, republish, repackage or present NAM Tools itself, its page structure or its tool content as your own product without permission.",
        "References to retailers, account management, commercial planning or common business processes do not imply endorsement by any third party.",
      ]}
    />
  );
}
